# Generated by Django 6.0.7 on 2026-07-24 07:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HospitalProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("hospital_code", models.CharField(max_length=6, unique=True)),
                ("name", models.CharField(max_length=50)),
                (
                    "department",
                    models.CharField(
                        choices=[
                            ("pathology", "병리과"),
                            ("pulmonology", "호흡기내과"),
                            ("oncology", "종양내과"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[("doctor", "의사"), ("pathologist", "병리사")],
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hospital_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
