# Generated by Django 6.0.7 on 2026-08-03 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientauth',
            name='phone_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
