# Generated by Django 6.0.7 on 2026-08-03 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_patientauth_phone_verified_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctorprofile',
            name='license_verified',
        ),
        migrations.RemoveField(
            model_name='doctorprofile',
            name='license_verified_at',
        ),
        migrations.RemoveField(
            model_name='patientauth',
            name='phone_verified_at',
        ),
    ]
