"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# FastAPI(realtime-service)가 같은 값으로 JWT를 검증해야 하므로 .env의
# DJANGO_SECRET_KEY로 공유한다. 값을 안 주면 기존 하드코딩값을 그대로 씀
# (기존 배포와 호환).
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY', 'django-insecure-la3ebbh6lr4i*235v&ndo12qazp@ow6&^3+bthoc9^p$)w5h_+')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["lung-cdss.kro.kr", "www.lung-cdss.kro.kr", "localhost", "127.0.0.1", "34.170.97.4"]


ALLOWED_HOSTS.append('backend')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'rest_framework',
    'rest_framework_simplejwt.token_blacklist',
    'drf_spectacular',
    'core',
    'cases',
    'accounts',
    'symptoms',
    'medications',
    'appointments',
    'intake',
    'communication',
    'clinical',
]

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    'EXCEPTION_HANDLER': 'core.exceptions.custom_exception_handler',
}

SPECTACULAR_SETTINGS = {
    'TITLE': 'LUNG-CDSS API',
    'DESCRIPTION': (
        '폐암(LUAD/LUSC) 진단·치료 지원 플랫폼 API. '
        '인증은 Bearer JWT (accounts 앱의 로그인 엔드포인트에서 발급).'
    ),
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
    'TAGS': [
        {'name': 'accounts', 'description': '의사/간호사/병리사(이메일+비번) · 환자(소셜+SMS) 인증'},
        {'name': 'cases', 'description': '케이스 검토 — AI결과(불변)/확정본(의사) 3단 분리'},
        {'name': 'symptoms', 'description': '일일 증상체크, 위험도 룰엔진'},
        {'name': 'medications', 'description': '복약스케줄/로그/순응도'},
        {'name': 'appointments', 'description': '예약 신청~확정~체크인'},
        {'name': 'intake', 'description': '문진표, QR 프로필공유'},
        {'name': 'communication', 'description': '채팅(REST), 알림'},
    ],
}

from datetime import timedelta
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(hours=12),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
}

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173",
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.environ.get('DB_NAME', 'lung_cdss'),
        'USER': os.environ.get('DB_USER', 'postgres'),
        'PASSWORD': os.environ.get('DB_PASSWORD', 'postgres'),
        'HOST': os.environ.get('DB_HOST', 'localhost'),
        'PORT': os.environ.get('DB_PORT', '5432'),
    }
}

AUTH_USER_MODEL = 'accounts.User'

# Django Admin 로그인 전용. User.USERNAME_FIELD가 UUID라 기본 ModelBackend는
# 이메일 문자열을 UUID로 파싱하려다 에러나므로 완전히 대체한다.
AUTHENTICATION_BACKENDS = ['accounts.backends.StaffEmailBackend']

# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Seoul'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

MOSEC_URL = os.environ.get("MOSEC_URL", "https://mosec-serving-369117807590.us-central1.run.app")
THUMBNAIL_SERVICE_URL = os.environ.get("THUMBNAIL_SERVICE_URL")


# ── Celery (예약 D-7/D-1 알림, 복약 재알림, FCM 발송, AI추론 백그라운드 처리) ──
CELERY_BROKER_URL = os.environ.get("CELERY_BROKER_URL", "redis://redis:6379/0")
CELERY_RESULT_BACKEND = CELERY_BROKER_URL
CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TASK_SERIALIZER = "json"
CELERY_TIMEZONE = TIME_ZONE  # Asia/Seoul

CELERY_BEAT_SCHEDULE = {
    "medication-due-reminders": {
        "task": "medications.tasks.send_due_medication_reminders",
        "schedule": 60.0,
    },
    "appointment-reminders-d7-d1": {
        "task": "appointments.tasks.send_appointment_reminders",
        "schedule": 3600.0,  # 매시 정각 실행, 대상 필터링은 task 내부에서
    },
    "medication-escalation-check": {
        "task": "medications.tasks.check_medication_compliance",
        "schedule": 3600.0,
    },
}

# accounts/views.py의 SMS 인증코드·소셜가입 임시세션이 여러 워커/프로세스에서
# 공유돼야 하므로 로컬메모리 캐시가 아닌 Redis 캐시를 사용.
CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": CELERY_BROKER_URL.replace("/0", "/1"),  # Celery와 DB 번호 분리
        "OPTIONS": {"CLIENT_CLASS": "django_redis.client.DefaultClient"},
    }
}
