# Generated by Django 6.0.7 on 2026-08-05 11:34

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("intake", "0002_alter_intakeform_submitted_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="IntakeTemplate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("version", models.PositiveIntegerField(default=1)),
                ("questions", models.JSONField()),
                ("is_active", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-version", "-updated_at"],
            },
        ),
    ]
