# Generated by Django 6.0.7 on 2026-07-31 11:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SymptomCheck',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('checked_at', models.DateTimeField(auto_now_add=True)),
                ('symptoms', models.JSONField()),
                ('risk_level', models.CharField(choices=[('green', '정상'), ('yellow', '주의'), ('red', '위험')], max_length=10)),
                ('visible_to_nurse', models.BooleanField(default=True)),
                ('nurse_reviewed', models.BooleanField(default=False)),
                ('nurse_reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('nurse_reviewed_by', models.ForeignKey(blank=True, limit_choices_to={'role': 'nurse'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_symptom_checks', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(limit_choices_to={'role': 'patient'}, on_delete=django.db.models.deletion.CASCADE, related_name='symptom_checks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-checked_at'],
            },
        ),
    ]
