# Generated by Django 6.0.7 on 2026-07-31 11:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('department', models.CharField(max_length=50)),
                ('requested_at_slot', models.DateTimeField()),
                ('confirmed_slot', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('requested', '요청됨'), ('confirmed', '확정'), ('reminded_d7', 'D-7 알림 발송'), ('reminded_d1', 'D-1 알림 발송'), ('checked_in', '방문완료'), ('completed', '진료완료'), ('cancelled', '취소'), ('no_show', '미방문')], default='requested', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('doctor', models.ForeignKey(limit_choices_to={'role': 'doctor'}, on_delete=django.db.models.deletion.CASCADE, related_name='doctor_appointments', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(limit_choices_to={'role': 'patient'}, on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to=settings.AUTH_USER_MODEL)),
                ('processed_by', models.ForeignKey(blank=True, limit_choices_to={'role': 'nurse'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_appointments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['requested_at_slot'],
            },
        ),
    ]
