# Generated by Django 6.0.7 on 2026-08-06 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0002_appointment_active_slot_constraint"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="proposal_reason",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="appointment",
            name="proposed_slot",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="appointment",
            name="rejection_reason",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="appointment",
            name="reviewed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="status",
            field=models.CharField(
                choices=[
                    ("requested", "요청됨"),
                    ("confirmed", "확정"),
                    ("reminded_d7", "D-7 알림 발송"),
                    ("reminded_d1", "D-1 알림 발송"),
                    ("checked_in", "방문완료"),
                    ("completed", "진료완료"),
                    ("cancelled", "취소"),
                    ("rejected", "반려"),
                    ("time_proposed", "대체 시간 제안"),
                    ("no_show", "미방문"),
                ],
                default="requested",
                max_length=20,
            ),
        ),
    ]
