DEFAULT_TEMPLATE_NAME = '폐암 환자 기본 문진'
DEFAULT_TEMPLATE_VERSION = 1

DEFAULT_QUESTIONS = [
    {
        'question_id': 'current_symptoms',
        'question_text': '현재 가장 불편한 증상을 선택해 주세요.',
        'question_type': 'multiple_choice',
        'options': ['기침', '가래', '객혈', '호흡곤란', '가슴 통증', '발열 또는 오한',
                    '피로감', '식욕 저하', '체중 감소', '메스꺼움 또는 구토', '어지럼증',
                    '통증', '특별한 증상 없음', '기타'],
        'required': True,
        'answer': [],
    },
    {
        'question_id': 'symptom_onset',
        'question_text': '증상은 언제부터 있었나요?',
        'question_type': 'single_choice',
        'options': ['오늘부터', '2~3일 전부터', '1주일 이내', '1~4주 전부터', '1개월 이상', '증상이 없음'],
        'required': True,
        'answer': None,
    },
    {
        'question_id': 'symptom_change',
        'question_text': '증상이 이전보다 심해졌나요?',
        'question_type': 'single_choice',
        'options': ['많이 심해짐', '조금 심해짐', '비슷함', '호전됨', '증상이 없음'],
        'required': True,
        'answer': None,
    },
    {
        'question_id': 'dyspnea_level',
        'question_text': '현재 호흡곤란 정도를 선택해 주세요.',
        'question_type': 'single_choice',
        'options': ['없음', '빠르게 걸을 때만 숨참', '평지를 걸을 때 숨참', '가벼운 활동에도 숨참',
                    '가만히 있어도 숨참'],
        'required': True,
        'answer': None,
    },
    {
        'question_id': 'hemoptysis',
        'question_text': '최근 객혈이 있었나요?',
        'question_type': 'single_choice',
        'options': ['없음', '가래에 소량의 피가 섞임', '한 번 이상 선명한 피가 나옴', '많은 양의 피가 나옴'],
        'required': True,
        'answer': None,
    },
    {
        'question_id': 'pain_level',
        'question_text': '현재 통증이 있나요?',
        'question_type': 'single_choice',
        'options': ['없음', '약함', '보통', '심함', '매우 심함'],
        'required': True, 'answer': None,
    },
    {
        'question_id': 'pain_description',
        'question_text': '통증이 있다면 위치와 양상을 작성해 주세요.',
        'question_type': 'text', 'options': [],
        'required': False, 'answer': '',
    },
    {
        'question_id': 'fever',
        'question_text': '최근 체온이 38도 이상이었나요?',
        'question_type': 'single_choice',
        'options': ['아니요', '예', '측정하지 않음'],
        'required': True, 'answer': None,
    },
    {
        'question_id': 'food_intake',
        'question_text': '최근 식사량은 어떠한가요?',
        'question_type': 'single_choice',
        'options': ['평소와 비슷함', '평소의 절반 이상', '평소의 절반 미만', '거의 먹지 못함'],
        'required': True, 'answer': None,
    },
    {
        'question_id': 'weight_change',
        'question_text': '최근 1개월 동안 체중 변화가 있었나요?',
        'question_type': 'single_choice',
        'options': ['변화 없음', '1~2kg 감소', '3~5kg 감소', '5kg 이상 감소', '체중 증가', '모름'],
        'required': True, 'answer': None,
    },
    {
        'question_id': 'medication_adherence',
        'question_text': '현재 처방받은 약을 복용하고 있나요?',
        'question_type': 'single_choice',
        'options': ['모두 복용 중', '일부만 복용 중', '복용하지 못함', '처방약 없음'],
        'required': True, 'answer': None,
    },
    {
        'question_id': 'medication_nonadherence_reason',
        'question_text': '약을 복용하지 못한 이유가 있나요?',
        'question_type': 'multiple_choice',
        'options': ['복용 시간을 잊음', '부작용이 걱정됨', '실제로 부작용이 발생함', '약이 부족함',
                    '복용 방법을 잘 모름', '증상이 좋아져서 중단함', '기타', '해당 없음'],
        'required': False, 'answer': [],
    },
    {
        'question_id': 'medication_side_effects',
        'question_text': '약 복용 후 불편한 증상이 있었나요?',
        'question_type': 'multiple_choice',
        'options': ['메스꺼움 또는 구토', '설사', '변비', '발진 또는 가려움', '어지럼증',
                    '심한 피로', '손발 저림', '식욕 저하', '기타', '없음'],
        'required': False, 'answer': [],
    },
    {
        'question_id': 'daily_activity',
        'question_text': '최근 일상생활 수행 정도를 선택해 주세요.',
        'question_type': 'single_choice',
        'options': ['평소처럼 생활 가능', '힘든 활동만 어려움', '가벼운 활동도 일부 어려움',
                    '대부분의 시간을 앉거나 누워 지냄', '거의 모든 일상생활에 도움이 필요함'],
        'required': True, 'answer': None,
    },
    {
        'question_id': 'questions_for_medical_staff',
        'question_text': '진료 시 의료진에게 꼭 묻고 싶은 내용을 작성해 주세요.',
        'question_type': 'text', 'options': [],
        'required': False, 'answer': '',
    },
]
