# Generated by Django 6.0.7 on 2026-07-22 14:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('specimen_id', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('uploaded', 'Uploaded'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='uploaded', max_length=20)),
                ('slide_gcs_path', models.TextField(blank=True, null=True)),
                ('heatmap_gcs_path', models.TextField(blank=True, null=True)),
                ('nuclei_density_score', models.FloatField(blank=True, null=True)),
                ('nuclei_density_level', models.CharField(blank=True, max_length=20, null=True)),
                ('nuclei_irregularity_score', models.FloatField(blank=True, null=True)),
                ('nuclei_irregularity_level', models.CharField(blank=True, max_length=20, null=True)),
                ('prediction_label', models.CharField(blank=True, choices=[('LUAD', 'LUAD'), ('LUSC', 'LUSC')], max_length=10, null=True)),
                ('luad_probability', models.FloatField(blank=True, null=True)),
                ('lusc_probability', models.FloatField(blank=True, null=True)),
                ('treatment_note', models.TextField(blank=True, null=True)),
                ('review_status', models.CharField(choices=[('ai_suggested', 'AI Suggested'), ('confirmed', 'Confirmed'), ('overridden', 'Overridden')], default='ai_suggested', max_length=20)),
                ('reviewer_note', models.TextField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('analyzed_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_cases', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='NucleiPatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('original_gcs_path', models.TextField()),
                ('overlay_gcs_path', models.TextField()),
                ('nuclei_count', models.IntegerField(blank=True, null=True)),
                ('attention_rank', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nuclei_patches', to='cases.case')),
            ],
            options={
                'ordering': ['attention_rank'],
            },
        ),
        migrations.CreateModel(
            name='GenePrediction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('gene_name', models.CharField(max_length=50)),
                ('likelihood', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gene_predictions', to='cases.case')),
            ],
            options={
                'ordering': ['gene_name'],
                'unique_together': {('case', 'gene_name')},
            },
        ),
    ]
