# Generated by Django 6.0.7 on 2026-07-31 11:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('specimen_id', models.CharField(max_length=100, unique=True)),
                ('status', models.CharField(choices=[('uploaded', 'Uploaded'), ('processing', 'Processing'), ('pending_review', 'Pending review'), ('confirmed', 'Confirmed'), ('failed', 'Failed')], default='uploaded', max_length=20)),
                ('current_step', models.CharField(blank=True, choices=[('uploaded', '업로드 확인'), ('preprocessing', '전처리'), ('feature_extraction', '특징 추출'), ('nuclei_detection', '핵 검출'), ('classification', '분류'), ('generating_result', '결과 생성')], max_length=30, null=True)),
                ('slide_gcs_path', models.TextField(blank=True, null=True)),
                ('slide_thumbnail_gcs_path', models.TextField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('analyzed_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('patient', models.ForeignKey(limit_choices_to={'role': 'patient'}, on_delete=django.db.models.deletion.CASCADE, related_name='cases', to=settings.AUTH_USER_MODEL)),
                ('uploaded_by', models.ForeignKey(blank=True, limit_choices_to={'role': 'pathologist'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_cases', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='AIAnalysisResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('model_version', models.CharField(max_length=50)),
                ('heatmap_gcs_path', models.TextField(blank=True, null=True)),
                ('nuclei_density_score', models.FloatField(blank=True, null=True)),
                ('nuclei_density_level', models.CharField(blank=True, max_length=20, null=True)),
                ('nuclei_irregularity_score', models.FloatField(blank=True, null=True)),
                ('nuclei_irregularity_level', models.CharField(blank=True, max_length=20, null=True)),
                ('prediction_label', models.CharField(blank=True, choices=[('LUAD', 'LUAD'), ('LUSC', 'LUSC')], max_length=10, null=True)),
                ('luad_probability', models.FloatField(blank=True, null=True)),
                ('lusc_probability', models.FloatField(blank=True, null=True)),
                ('treatment_note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_results', to='cases.case')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CaseFinding',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mode', models.CharField(choices=[('heatmap', '히트맵'), ('overlay', '오버레이'), ('original', '원본')], max_length=10)),
                ('strokes', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='findings', to='cases.case')),
                ('user', models.ForeignKey(limit_choices_to={'role': 'doctor'}, on_delete=django.db.models.deletion.CASCADE, related_name='case_findings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CaseReviewLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('confirmed', '그대로 승인'), ('edited', '수정 후 확정')], max_length=10)),
                ('subtype_at_time', models.CharField(max_length=10)),
                ('note_at_time', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_logs', to='cases.case')),
                ('reviewer', models.ForeignKey(limit_choices_to={'role': 'doctor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='review_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NucleiPatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('original_gcs_path', models.TextField()),
                ('overlay_gcs_path', models.TextField()),
                ('nuclei_count', models.IntegerField(blank=True, null=True)),
                ('attention_rank', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ai_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nuclei_patches', to='cases.aianalysisresult')),
            ],
            options={
                'ordering': ['attention_rank'],
            },
        ),
        migrations.CreateModel(
            name='ConfirmedFinding',
            fields=[
                ('case', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='confirmed_finding', serialize=False, to='cases.case')),
                ('final_subtype', models.CharField(max_length=10)),
                ('final_note', models.TextField(blank=True)),
                ('confirmed_at', models.DateTimeField(auto_now_add=True)),
                ('based_on_result', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='confirmations', to='cases.aianalysisresult')),
                ('confirmed_by', models.ForeignKey(limit_choices_to={'role': 'doctor'}, on_delete=django.db.models.deletion.PROTECT, related_name='confirmed_findings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CaseFavorite',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='cases.case')),
                ('user', models.ForeignKey(limit_choices_to={'role': 'doctor'}, on_delete=django.db.models.deletion.CASCADE, related_name='favorite_cases', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'case'), name='uniq_user_case_favorite')],
            },
        ),
        migrations.CreateModel(
            name='GenePrediction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('gene_name', models.CharField(max_length=50)),
                ('likelihood', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ai_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gene_predictions', to='cases.aianalysisresult')),
            ],
            options={
                'ordering': ['gene_name'],
                'constraints': [models.UniqueConstraint(fields=('ai_result', 'gene_name'), name='uniq_ai_result_gene')],
            },
        ),
    ]
