# Generated by Django 6.0.7 on 2026-07-23 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='current_step',
            field=models.CharField(blank=True, choices=[('uploaded', '업로드 확인'), ('preprocessing', '전처리'), ('feature_extraction', '특징 추출'), ('nuclei_detection', '핵 검출'), ('classification', '분류'), ('generating_result', '결과 생성')], max_length=30, null=True),
        ),
    ]
