# Generated by Django 6.0.7 on 2026-08-05 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="case",
            name="status",
            field=models.CharField(
                choices=[
                    ("uploaded", "Uploaded"),
                    ("processing", "Processing"),
                    ("pending_review", "Pending review"),
                    ("confirmed", "Confirmed"),
                    ("rejected", "Rejected"),
                    ("failed", "Failed"),
                ],
                default="uploaded",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="casereviewlog",
            name="action",
            field=models.CharField(
                choices=[
                    ("rejected", "미승인"),
                    ("confirmed", "그대로 승인"),
                    ("edited", "수정 후 확정"),
                ],
                max_length=10,
            ),
        ),
    ]
