# Generated by Django 6.0.7 on 2026-07-23 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0002_case_current_step'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='slide_thumbnail_gcs_path',
            field=models.TextField(blank=True, null=True),
        ),
    ]
