# Generated by Django 6.0.7 on 2026-07-24 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0003_case_slide_thumbnail_gcs_path"),
    ]

    operations = [
        migrations.AlterField(
            model_name="case",
            name="review_status",
            field=models.CharField(
                choices=[
                    ("pending", "대기"),
                    ("confirmed", "승인"),
                    ("rejected", "미승인"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
