# Generated by Django 6.0.7 on 2026-07-25 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0004_alter_case_review_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='specimen_id',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
